spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Swagger + H2 호환성 확보용
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
      ssl:
        trust: smtp.gmail.com

# Solapi SMS 설정
solapi:
  api-key: ${SOLAPI_API_KEY:your-api-key}
  api-secret: ${SOLAPI_API_SECRET:your-api-secret}
  from: ${SOLAPI_FROM:your-phone-number}

