spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # Swagger + H2 호환성 확보용
  mail:
    host: smtp.gmail.com
    port: 587
    username: danny.jung1223@gmail.com
    password: nlpp zyvx epvp kccz  # Gmail App Password
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
      ssl:
        trust: smtp.gmail.com

# Solapi SMS 설정
solapi:
  api-key: NCSYDU7LGXZCO670
  api-secret: LPBBWIRDZWCKNFLJNZ8HQ7OQ1HB2LCKY
  from: 01099750327

